  - name: INFO MESSAGE FOR DOCKERHOST PLAYBOOK
    debug:
      msg: "USE -e install='y' for installing and reload, -e config='y' for rollout configs without reload, -e reload='y' for reload"
  - name: create directory for ansible custom facts
    file:
      state: "directory"
      recurse: yes
      path: "/etc/ansible/facts.d"
  - name: install custom impi fact
    copy:
      src: files/docker.fact
      dest: /etc/ansible/facts.d
      mode: 0755
  - name: re-read facts after adding custom fact
    setup: ~

  - debug:
      msg: "Docker: {{ansible_local.docker}}"

  - name: check docker package
    yum: name=docker-ce state=present
    check_mode: true
    register: docker

  - debug:
      msg: "Package: {{docker}}"

  - name: install
    block:
          - name: install docker compose
            copy:
              src:  binary/docker-compose
              dest: /usr/bin/docker-compose

          - name: install docker packages
            yum: state=present name=docker-ce
    when:
      - install is defined

  - name: configs
    block:
      - name: sysctl
        sysctl: name=vm.max_map_count value=262144 state=present
      - name: sysctl
        sysctl: name=fs.file-max value=65500 state=present
      - name: ulimit
        shell: echo -e "*\tsoft\tnofile\t1000000\n*\thard\tnofile\t1000000\n" > /etc/security/limits.d/5-nofile.conf
      - name: create directory for docker configs
        file:
          state: "directory"
          recurse: yes
          path: "/etc/docker"
      - name: create directory for systemd overide
        file:
          state: directory
          recurse: yes
          path: "/etc/systemd/system/docker.service.d"
      - name: template daemon.json upload
        template:
           src: docker/configs/daemon.json.tpl
           dest: /etc/docker/daemon.json
           owner: root
           group: root
           mode: "u=rw,g=,o="
      - name: template systemd overide docker service
        template:
           src: docker/systemd/docker.conf
           dest: /etc/systemd/system/docker.service.d/docker.conf
           owner: root
           group: root
           mode: "u=rw,g=r,o=r"
    when: (config is defined) or (install is defined)

  
  - name: reloading service
    debug: msg="Reloading"
    changed_when: True
    notify: reload_docker
    when: (reload is defined) or (install is defined)


 
